services:
  maestro:
    image: altlinux.space/alt-orchestra-dev/maestro-dev:latest
    ports:
      - 127.0.0.1:4466:4466
      - 127.0.0.1:5000:5000
    environment:
      MAESTRO_API_USER: $MAESTRO_API_USER
      MAESTRO_API_UID: $MAESTRO_API_UID
      MAESTRO_FRONTEND_HOST: 0.0.0.0
      MAESTRO_API_HOST: 0.0.0.0
      MAESTRO_API_KEYS: $MAESTRO_API_KEYS
      MAESTRO_CORS_ORIGINS: $MAESTRO_CORS_ORIGINS
      MAESTRO_API_WHITELIST: $MAESTRO_API_WHITELIST
      FLASK_DEBUG: 1
      MAESTRO_API_DEBUG: True
    volumes:
      - /home/$MAESTRO_API_USER/.maestro:/home/maestro/.maestro
      - /home/$MAESTRO_API_USER/.kube:/home/maestro/.kube
